### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by LARSABI** [davide-acanfora/spotify-account-generator#9]
good evening, i need some help :(

console say´s 1/1: Could not create the account, some errors occurred!

**Comment by davide-acanfora** [comment]
It works for me. I've just updated the script, give it a try

**Comment by ZeroDiscord** [comment]
```sh
Could not create the account, some errors occurred
{'generic_error': 'You seem to be using a proxy service. Please turn off these services and try again. For more help, please contact customer service.'}
```
This is as spotify does not allow proxies, I was trying to make a similar generator in javascript although failed to do so even after buying premium socks5 proxies.

**Comment by davide-acanfora** [comment]
It's probably because Spotify over time creates a list of known proxies and saves their IP addresses. Surely the proxy you paid for is already in their list and is stored as such, so for security reasons and to mitigate the use of bots and scripts like the one in this repository Spotify will discard all requests coming from them (clearly demonstrated by the error message you reported)

**Comment by LARSABI** [comment]
Is it possible to get the Bot without the Proxy Function?

Sorry for my bad english

**Comment by davide-acanfora** [comment]
Hi, I don't think I understand. The script as it is now has no proxy function already. Instead, if you are asking me to implement it, well it is surely possible but unfortunately I have not planned to do it yet at the moment. I'll keep that in mind though. Thanks.
